@startuml

title __DICT's Class Diagram__\n

  namespace com.yyzy.constellation {
    namespace dict {
      class com.yyzy.constellation.dict.BaseSearchActivity {
          + gridDatas : List<ListBean>
          + listView : ExpandableListView
          + page : int
          + pageSize : int
          + totalPage : int
          + tv : TextView
          + url : String
          + word : String
          - childDatas : List<List<ResultDTO>>
          - groupDatas : List<String>
          - imgBack : ImageView
          - selChildPos : int
          - selGroupPos : int
          + getDataAlertWord()
          + initData()
          + initGridDada()
          + loadData()
          {static} + loadNetDataResult()
          + onCancelled()
          + onClick()
          + onError()
          + onFinished()
          + onSuccess()
          + refreshDataByGV()
          + setExlvListener()
          + setGVListener()
          # onCreate()
          - initView()
          - writeDBByThread()
      }
    }
  }
  

  com.yyzy.constellation.dict.BaseSearchActivity .up.|> org.xutils.common.Callback.CommonCallback
  com.yyzy.constellation.dict.BaseSearchActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.yyzy.constellation.dict.BaseSearchActivity o-- com.yyzy.constellation.dict.adapter.SearchLeftAdapter : adapter
  com.yyzy.constellation.dict.BaseSearchActivity o-- com.yyzy.constellation.dict.adapter.SearchRightAdapter : gridViewAdapter
  com.yyzy.constellation.dict.BaseSearchActivity o-- com.yyzy.constellation.utils.DiyProgressDialog : dialog
  com.yyzy.constellation.dict.BaseSearchActivity o-- com.handmark.pulltorefresh.library.PullToRefreshGridView : gridView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
