@startuml

title __UTILS's Class Diagram__\n

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.AlertDialogUtils {
          {static} + alert : AlertDialog
          {static} + builder : Builder
          {static} + dialog_cancelBtn : Button
          {static} + dialog_confirmBtn : Button
          {static} + mOnDialogButtonClickListener : OnDialogButtonClickListener
          {static} + tv_dialog_content : TextView
          {static} + tv_dialog_title : TextView
          {static} - view_custom : View
          {static} + getInstance()
          + setMonDialogButtonClickListener()
          {static} + setWindowSize()
          {static} + showConfirmDialog()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.AlertDialogUtils.OnDialogButtonClickListener {
          {abstract} + onNegativeButtonClick()
          {abstract} + onPositiveButtonClick()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.AssetsUtils {
          {static} - contentLogoImgMap : Map<String, Bitmap>
          {static} - logeImgMap : Map<String, Bitmap>
          {static} + getBitmapFromAssets()
          {static} + getContentLogoImgMap()
          {static} + getJsonFromAssets()
          {static} + getLogeImgMap()
          {static} + saveBitmapFromAssets()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.BitmapUtils {
          {static} + base64ToBitmap()
          {static} + bitmapToBase64()
          {static} + urlToBitmap()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.CameraUtils {
          {static} + ImgUpdateDirection()
          {static} + compression()
          {static} + getImageBeforeKitKatPath()
          {static} + getImageOnKitKatPath()
          {static} + getImagePath()
          {static} + getSelectPhotoIntent()
          {static} + getTakePhotoIntent()
          {static} + hasSdcard()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.CommonUtils {
          {static} + FILE_BUSHOU : String
          {static} + FILE_PINYIN : String
          {static} + TABLE_COLLECT_CYUTB : String
          {static} + TABLE_COLLECT_WORDTB : String
          {static} + TABLE_CYUTB : String
          {static} + TABLE_PYWORDTB : String
          {static} + TABLE_WORDTB : String
          {static} + TYPE_BUSHOU : int
          {static} + TYPE_PINYIN : int
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.Constellation {
          {static} - httpQueue : RequestQueue
          {static} + getHttpQueue()
          + onCreate()
          - initImageLoader()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.DialogUtils {
          {static} + showToast()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.DiyProgressDialog {
          + messageTv : TextView
          + DiyProgressDialog()
          + DiyProgressDialog()
          + DiyProgressDialog()
          + dismiss()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.FileUtil {
          {static} + getSaveFile()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.FourFiguresNumberCode {
          {static} - BASE_PADDING_LEFT : int
          {static} - BASE_PADDING_TOP : int
          {static} - CHARS : char[]
          {static} - DEFAULT_CODE_LENGTH : int
          {static} - DEFAULT_FONT_SIZE : int
          {static} - DEFAULT_HEIGHT : int
          {static} - DEFAULT_LINE_NUMBER : int
          {static} - DEFAULT_WIDTH : int
          {static} - RANGE_PADDING_LEFT : int
          {static} - RANGE_PADDING_TOP : int
          - base_padding_left : int
          - base_padding_top : int
          {static} - bmpFourFiguresNumberCode : FourFiguresNumberCode
          - code : String
          - codeLength : int
          - font_size : int
          - height : int
          - line_number : int
          - padding_left : int
          - padding_top : int
          - random : Random
          - range_padding_left : int
          - range_padding_top : int
          - width : int
          + createBitmap()
          + getCode()
          {static} + getInstance()
          - createCode()
          - drawLine()
          - randomColor()
          - randomColor()
          - randomPadding()
          - randomTextStyle()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.HttpUtils {
          {static} + getJSONFromNet()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.KeyBoardUtils {
          ~ listener : OnKeyboardActionListener
          - editText : EditText
          - k1 : Keyboard
          - keyboardView : KeyboardView
          + KeyBoardUtils()
          + hideKeyboard()
          + setOnEnSureListener()
          + showKeyboard()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.KeyBoardUtils.OnEnSureListener {
          {abstract} + onEnSure()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.LoadDataAsyncTask {
          - context : Context
          - isShowDialog : boolean
          + LoadDataAsyncTask()
          + initDialog()
          # doInBackground()
          # onPostExecute()
          # onPreExecute()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.LoadDataAsyncTask.OnGetNetDataListener {
          {abstract} + onSuccess()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.MyEditText {
          - mContext : Context
          - mDeleteDrawable : Drawable
          - watcher : TextWatcher
          + MyEditText()
          + MyEditText()
          + MyEditText()
          + onTouchEvent()
          - dip2px()
          - init()
          - setClearIconVisible()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.MyGridView {
          + MyGridView()
          + MyGridView()
          # onMeasure()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.MyPasswordEditText {
          - mToggleDrawable : Drawable
          + MyPasswordEditText()
          + MyPasswordEditText()
          + MyPasswordEditText()
          + afterTextChanged()
          + beforeTextChanged()
          + onFocusChange()
          + onTextChanged()
          + onTouchEvent()
          + setShakeAnimation()
          + setToggleIconVisible()
          + shakeAnimation()
          - init()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.MyToast {
          {static} - TYPE_FALSE : int
          {static} - TYPE_HIDE : int
          {static} - TYPE_TRUE : int
          {static} - toast : MyToast
          {static} - toast_img : ImageView
          + MyToast()
          + cancel()
          {static} + cancelToast()
          + show()
          {static} + showText()
          {static} + showText()
          {static} + showText()
          {static} + showText()
          {static} - initToast()
          {static} - showToast()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.Mydialog {
          ~ mActivity : Activity
          ~ mBtnCancel : Button
          ~ mBtnConnect : Button
          ~ mContext : Context
          ~ text_read : TextView
          + onClick()
          # Mydialog()
          # onCreate()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.PatternUtils {
          {static} + removeAll()
          {static} + removeDigital()
          {static} + removeLetter()
          {static} + removePunctuation()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.RecognizeService {
          {static} + recAccurate()
          {static} + recAccurateBasic()
          {static} + recBankCard()
          {static} + recBusinessCard()
          {static} + recBusinessLicense()
          {static} + recCustom()
          {static} + recDrivingLicense()
          {static} + recGeneral()
          {static} + recGeneralBasic()
          {static} + recGeneralEnhanced()
          {static} + recHandwriting()
          {static} + recLicensePlate()
          {static} + recLottery()
          {static} + recNumbers()
          {static} + recPassport()
          {static} + recQrcode()
          {static} + recReceipt()
          {static} + recVatInvoice()
          {static} + recVehicleLicense()
          {static} + recWebimage()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.RecognizeService.ServiceListener {
          {abstract} + onResult()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.SPUtils {
          {static} - NAME : String
          {static} + getBoolean()
          {static} + getInt()
          {static} + getString()
          {static} + putBoolean()
          {static} + putInt()
          {static} + putString()
          {static} + remove()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.SplitEditText {
          {static} - DEFAULT_CIPHER_MASK : String
          - isDraw : boolean
          - isFakeBoldText : boolean
          - mBorderColor : int
          - mBorderCornerRadius : float
          - mBorderSpacing : float
          - mBorderStyle : int
          - mBoxBackgroundColor : int
          - mBoxHeight : float
          - mBoxWidth : float
          - mCipherMask : String
          - mFocusBorderColor : int
          - mInputBorderColor : int
          - mMaxLength : int
          - mPaint : Paint
          - mPath : Path
          - mRadiusFirstArray : float[]
          - mRadiusLastArray : float[]
          - mRectF : RectF
          - mStrokeWidth : float
          - mTextLength : int
          - mTextStyle : int
          + SplitEditText()
          + SplitEditText()
          + SplitEditText()
          + getBorderColor()
          + getBorderCornerRadius()
          + getBorderSpacing()
          + getBorderStyle()
          + getBoxBackgroundColor()
          + getCipherMask()
          + getFocusBorderColor()
          + getInputBorderColor()
          + getTextStyle()
          + setBorderColor()
          + setBorderCornerRadius()
          + setBorderSpacing()
          + setBorderStyle()
          + setBoxBackgroundColor()
          + setCipherMask()
          + setFakeBoldText()
          + setFocusBorderColor()
          + setInputBorderColor()
          + setOnTextInputListener()
          + setTextStyle()
          # onDetachedFromWindow()
          # onDraw()
          # onFocusChanged()
          # onSelectionChanged()
          # onSizeChanged()
          # onTextChanged()
          - drawBorder()
          - drawBorderBox()
          - drawBorderLine()
          - drawBorders()
          - drawText()
          - getRoundRectPath()
          - init()
          - refreshView()
          - updateSizeChanged()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.SplitEditText.BorderStyle {
          {static} + BOX : int
          {static} + LINE : int
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      abstract class com.yyzy.constellation.utils.SplitEditText.OnSimpleTextInputListener {
          + onTextInputChanged()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.SplitEditText.OnTextInputListener {
          {abstract} + onTextInputChanged()
          {abstract} + onTextInputCompleted()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.SplitEditText.TextStyle {
          {static} + CIPHER_TEXT : int
          {static} + PLAIN_TEXT : int
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.StringUtils {
          {static} + URLS : List<String>
          {static} + string : List<String>
          {static} + setContent()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.SwipeCaptchaView {
          + offset : int
          # mHeight : int
          # mWidth : int
          - isDrawMask : boolean
          - isMatchMode : boolean
          - isShowSuccessAnim : boolean
          - mCaptchaHeight : int
          - mCaptchaPath : Path
          - mCaptchaWidth : int
          - mCaptchaX : int
          - mCaptchaY : int
          - mDragerOffset : int
          - mFailAnim : ValueAnimator
          - mMaskBitmap : Bitmap
          - mMaskPaint : Paint
          - mMaskShadowBitmap : Bitmap
          - mMaskShadowPaint : Paint
          - mMatchDeviation : float
          - mPaint : Paint
          - mPorterDuffXfermode : PorterDuffXfermode
          - mRandom : Random
          - mSuccessAnim : ValueAnimator
          - mSuccessAnimOffset : int
          - mSuccessPaint : Paint
          - mSuccessPath : Path
          + SwipeCaptchaView()
          + SwipeCaptchaView()
          + SwipeCaptchaView()
          + createCaptcha()
          {static} + dp2px()
          {static} + drawPartCircle()
          + getMaxSwipeValue()
          + matchCaptcha()
          + resetCaptcha()
          + setCurrentSwipeValue()
          + setOnCaptchaMatchCallback()
          # onDraw()
          # onSizeChanged()
          - createCaptchaPath()
          - createMask()
          - createMatchAnim()
          - getMaskBitmap()
          - init()
          - resetFlags()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      interface com.yyzy.constellation.utils.SwipeCaptchaView.OnCaptchaMatchCallback {
          {abstract} + matchFailed()
          {abstract} + matchSuccess()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.URLContent {
          {static} + BASE_URL : String
          {static} + CHENGYUKEY : String
          {static} + DICTKEY : String
          {static} + DICT_EVERYDAY_URL : String
          {static} + bushourul : String
          {static} + chengyuurl : String
          {static} + entertainment_url : String
          {static} + fashion_url : String
          {static} + finance_url : String
          {static} + headline_url : String
          {static} + home_url : String
          {static} + info_url : String
          {static} + internation_url : String
          {static} + key : String
          {static} + military_url : String
          {static} + pinyinurl : String
          {static} + science_url : String
          {static} + society_url : String
          {static} + sport_url : String
          {static} + wordurl : String
          {static} - KEY : String
          {static} - index_url : String
          {static} - temp_url : String
          {static} + getBushouurl()
          {static} + getChengyuurl()
          {static} + getHistoryDescURL()
          {static} + getIndex_url()
          {static} + getLaohuangliURL()
          {static} + getLuckURL()
          {static} + getPartnerURL()
          {static} + getPinyinurl()
          {static} + getTemp_url()
          {static} + getTodayHistoryURL()
          {static} + getWordurl()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace utils {
      class com.yyzy.constellation.utils.ViewUtil {
          {static} + getMaxLength()
          {static} + hideAllInputMethod()
          {static} + hideOneInputMethod()
      }
    }
  }
  

  com.yyzy.constellation.utils.AlertDialogUtils +-down- com.yyzy.constellation.utils.AlertDialogUtils.OnDialogButtonClickListener
  com.yyzy.constellation.utils.Constellation -up-|> android.app.Application
  com.yyzy.constellation.utils.DiyProgressDialog -up-|> android.app.Dialog
  com.yyzy.constellation.utils.KeyBoardUtils o-- com.yyzy.constellation.utils.KeyBoardUtils.OnEnSureListener : onEnSureListener
  com.yyzy.constellation.utils.KeyBoardUtils +-down- com.yyzy.constellation.utils.KeyBoardUtils.OnEnSureListener
  com.yyzy.constellation.utils.LoadDataAsyncTask -up-|> android.os.AsyncTask
  com.yyzy.constellation.utils.LoadDataAsyncTask o-- com.yyzy.constellation.utils.DiyProgressDialog : dialog
  com.yyzy.constellation.utils.LoadDataAsyncTask o-- com.yyzy.constellation.utils.LoadDataAsyncTask.OnGetNetDataListener : listener
  com.yyzy.constellation.utils.LoadDataAsyncTask +-down- com.yyzy.constellation.utils.LoadDataAsyncTask.OnGetNetDataListener
  com.yyzy.constellation.utils.MyEditText -up-|> androidx.appcompat.widget.AppCompatEditText
  com.yyzy.constellation.utils.MyGridView -up-|> android.widget.GridView
  com.yyzy.constellation.utils.MyPasswordEditText .up.|> android.text.TextWatcher
  com.yyzy.constellation.utils.MyPasswordEditText .up.|> android.view.View.OnFocusChangeListener
  com.yyzy.constellation.utils.MyPasswordEditText -up-|> androidx.appcompat.widget.AppCompatEditText
  com.yyzy.constellation.utils.MyToast -up-|> android.widget.Toast
  com.yyzy.constellation.utils.Mydialog .up.|> android.view.View.OnClickListener
  com.yyzy.constellation.utils.Mydialog -up-|> androidx.appcompat.app.AlertDialog
  com.yyzy.constellation.utils.RecognizeService +-down- com.yyzy.constellation.utils.RecognizeService.ServiceListener
  com.yyzy.constellation.utils.SplitEditText -up-|> androidx.appcompat.widget.AppCompatEditText
  com.yyzy.constellation.utils.SplitEditText o-- com.yyzy.constellation.utils.SplitEditText.OnTextInputListener : mOnTextInputListener
  com.yyzy.constellation.utils.SplitEditText +-down- com.yyzy.constellation.utils.SplitEditText.BorderStyle
  com.yyzy.constellation.utils.SplitEditText +-down- com.yyzy.constellation.utils.SplitEditText.OnSimpleTextInputListener
  com.yyzy.constellation.utils.SplitEditText +-down- com.yyzy.constellation.utils.SplitEditText.OnTextInputListener
  com.yyzy.constellation.utils.SplitEditText +-down- com.yyzy.constellation.utils.SplitEditText.TextStyle
  com.yyzy.constellation.utils.SplitEditText.OnSimpleTextInputListener .up.|> com.yyzy.constellation.utils.SplitEditText.OnTextInputListener
  com.yyzy.constellation.utils.SwipeCaptchaView -up-|> androidx.appcompat.widget.AppCompatImageView
  com.yyzy.constellation.utils.SwipeCaptchaView o-- com.yyzy.constellation.utils.SwipeCaptchaView.OnCaptchaMatchCallback : onCaptchaMatchCallback
  com.yyzy.constellation.utils.SwipeCaptchaView +-down- com.yyzy.constellation.utils.SwipeCaptchaView.OnCaptchaMatchCallback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
