@startuml

title __BEAN's Class Diagram__\n

  namespace com.yyzy.constellation {
    namespace tally {
      namespace bean {
        class com.yyzy.constellation.tally.bean.BarCharItemBean {
            - day : int
            - month : int
            - sumMoney : float
            - year : int
            + BarCharItemBean()
            + BarCharItemBean()
            + getDay()
            + getMonth()
            + getSumMoney()
            + getYear()
            + setDay()
            + setMonth()
            + setSumMoney()
            + setYear()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace bean {
        class com.yyzy.constellation.tally.bean.ChartLvItemBean {
            - img : int
            - ratio : float
            - sumMoney : float
            - type : String
            + ChartLvItemBean()
            + ChartLvItemBean()
            + getImg()
            + getRatio()
            + getSumMoney()
            + getType()
            + setImg()
            + setRatio()
            + setSumMoney()
            + setType()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace bean {
        class com.yyzy.constellation.tally.bean.GvTypeBean {
            - id : int
            - outOrIn : int
            - selectImg : int
            - typeName : String
            - unSelectImg : int
            + GvTypeBean()
            + GvTypeBean()
            + getId()
            + getOutOrIn()
            + getSelectImg()
            + getTypeName()
            + getUnSelectImg()
            + setId()
            + setOutOrIn()
            + setSelectImg()
            + setTypeName()
            + setUnSelectImg()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace bean {
        class com.yyzy.constellation.tally.bean.TallyLvItemBean {
            - beizhu : String
            - day : int
            - id : int
            - img : int
            - money : float
            - month : int
            - outOrIn : int
            - time : String
            - typeName : String
            - year : int
            + TallyLvItemBean()
            + TallyLvItemBean()
            + TallyLvItemBean()
            + getBeizhu()
            + getDay()
            + getId()
            + getImg()
            + getMoney()
            + getMonth()
            + getOutOrIn()
            + getTime()
            + getTypeName()
            + getYear()
            + setBeizhu()
            + setDay()
            + setId()
            + setImg()
            + setMoney()
            + setMonth()
            + setMonth()
            + setOutOrIn()
            + setTime()
            + setTypeName()
            + setYear()
            + toString()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
