@startuml

title __DB's Class Diagram__\n

  namespace com.yyzy.constellation {
    namespace dict {
      namespace db {
        class com.yyzy.constellation.dict.db.DBOpenHelper {
            + DBOpenHelper()
            + onCreate()
            + onUpgrade()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace dict {
      namespace db {
        class com.yyzy.constellation.dict.db.DBmanager {
            {static} - database : SQLiteDatabase
            {static} + delAllCyFromCyutb()
            {static} + delWhereCyFromCyutb()
            {static} + deleteCyuToCollCyutb()
            {static} + deleteZiToCollwordtb()
            {static} + initDB()
            {static} + insertCyToCyutb()
            {static} + insertCyuToCollCyutb()
            {static} + insertListToPywordtb()
            {static} + insertWordToPywordtb()
            {static} + insertWordToWordtb()
            {static} + insertZiToCollwordtb()
            {static} + isExistCyuInCollCyutb()
            {static} + isExistZiInCollwordtb()
            {static} + listToString()
            {static} + queryAllCyFromCyutb()
            {static} + queryAllInCollCyutb()
            {static} + queryAllInCollwordtb()
            {static} + queryBsWordFromPywordtb()
            {static} + queryCyFromCyutb()
            {static} + queryPyWordFromPywordtb()
            {static} + queryWordFromWordtb()
            {static} + stringToList()
        }
      }
    }
  }
  

  com.yyzy.constellation.dict.db.DBOpenHelper -up-|> android.database.sqlite.SQLiteOpenHelper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
