@startuml

title __NEWS's Class Diagram__\n

  namespace com.yyzy.constellation {
    namespace news {
      class com.yyzy.constellation.news.AddItemActivity {
          - imgBack : ImageView
          - lv : ListView
          - mData : List<TypeBean>
          - tvTitle : TextView
          + onClick()
          + onKeyDown()
          # initData()
          # initLayout()
          # initView()
          # onPause()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace news {
      class com.yyzy.constellation.news.NewsActivity {
          - fragmentList : List<Fragment>
          - imgAdd : ImageView
          - imgBack : ImageView
          - selectTypeList : List<TypeBean>
          - viewPager : ViewPager
          + onClick()
          + onKeyDown()
          # initData()
          # initLayout()
          # initView()
          # onRestart()
          - initPager()
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace news {
      class com.yyzy.constellation.news.NewsInfoActivity {
          - imgBack : ImageView
          - title : String
          - tvTitle : TextView
          - url : String
          - webView : WebView
          + loadProgress()
          + onClick()
          + onKeyDown()
          # initData()
          # initLayout()
          # initView()
          # onDestroy()
          - addImgClickListener()
          - closeDialog()
      }
    }
  }
  

  com.yyzy.constellation.news.AddItemActivity .up.|> android.view.View.OnClickListener
  com.yyzy.constellation.news.AddItemActivity -up-|> com.yyzy.constellation.activity.BaseActivity
  com.yyzy.constellation.news.AddItemActivity o-- com.yyzy.constellation.news.adapter.AddItemAdapter : addItemAdapter
  com.yyzy.constellation.news.NewsActivity .up.|> android.view.View.OnClickListener
  com.yyzy.constellation.news.NewsActivity -up-|> com.yyzy.constellation.activity.BaseActivity
  com.yyzy.constellation.news.NewsActivity o-- com.yyzy.constellation.news.adapter.NewsInfoAdapter : newsInfoAdapter
  com.yyzy.constellation.news.NewsActivity o-- com.yyzy.constellation.news.view.PagerSlidingTabStrip : pagerStrip
  com.yyzy.constellation.news.NewsInfoActivity .up.|> android.view.View.OnClickListener
  com.yyzy.constellation.news.NewsInfoActivity -up-|> com.yyzy.constellation.activity.BaseActivity
  com.yyzy.constellation.news.NewsInfoActivity o-- com.yyzy.constellation.utils.DiyProgressDialog : mDialog


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
