@startuml

title __FRAGMENT's Class Diagram__\n

  namespace com.yyzy.constellation {
    namespace tally {
      namespace fragment {
        abstract class com.yyzy.constellation.tally.fragment.BaseChartFragment {
            + barChart : BarChart
            + mData : List<ChartLvItemBean>
            + tv : TextView
            - lv : ListView
            - month : int
            - year : int
            + BaseChartFragment()
            + loadData()
            + onCreateView()
            + setData()
            # setAxis()
            {abstract} # setAxisData()
            {abstract} # setYAxis()
            - addLVHeaderView()
            - initView()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace fragment {
        class com.yyzy.constellation.tally.fragment.InComeChartFragment {
            ~ month : int
            ~ outOrIn : int
            ~ year : int
            + InComeChartFragment()
            + onResume()
            # setAxisData()
            # setYAxis()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace fragment {
        class com.yyzy.constellation.tally.fragment.InComeFragment {
            + loadData()
            # insertDataToDb()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace fragment {
        class com.yyzy.constellation.tally.fragment.OutComeChartFragment {
            ~ month : int
            ~ outOrIn : int
            ~ year : int
            + OutComeChartFragment()
            + onResume()
            # setAxisData()
            # setYAxis()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace fragment {
        class com.yyzy.constellation.tally.fragment.OutComeFragment {
            + loadData()
            # insertDataToDb()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace tally {
      namespace fragment {
        abstract class com.yyzy.constellation.tally.fragment.TallyBaseFragment {
            ~ etMoney : EditText
            ~ gv : GridView
            ~ imgType : ImageView
            ~ keyboardView : KeyboardView
            ~ mData : List<GvTypeBean>
            ~ tvBeizhu : TextView
            ~ tvTime : TextView
            ~ tvType : TextView
            - timeHour : String
            - timeMinute : String
            + TallyBaseFragment()
            + loadData()
            + onClick()
            + onCreate()
            + onCreateView()
            {abstract} # insertDataToDb()
            - initData()
            - initView()
            - setInitTime()
            - setListener()
            - showBeizhuDialog()
            - showTimeDialog()
        }
      }
    }
  }
  

  com.yyzy.constellation.tally.fragment.BaseChartFragment -up-|> androidx.fragment.app.Fragment
  com.yyzy.constellation.tally.fragment.BaseChartFragment o-- com.yyzy.constellation.tally.adapter.ChartLvItemAdapter : chartLvItemAdapter
  com.yyzy.constellation.tally.fragment.InComeChartFragment -up-|> com.yyzy.constellation.tally.fragment.BaseChartFragment
  com.yyzy.constellation.tally.fragment.InComeFragment -up-|> com.yyzy.constellation.tally.fragment.TallyBaseFragment
  com.yyzy.constellation.tally.fragment.OutComeChartFragment -up-|> com.yyzy.constellation.tally.fragment.BaseChartFragment
  com.yyzy.constellation.tally.fragment.OutComeFragment -up-|> com.yyzy.constellation.tally.fragment.TallyBaseFragment
  com.yyzy.constellation.tally.fragment.TallyBaseFragment .up.|> android.view.View.OnClickListener
  com.yyzy.constellation.tally.fragment.TallyBaseFragment -up-|> androidx.fragment.app.Fragment
  com.yyzy.constellation.tally.fragment.TallyBaseFragment o-- com.yyzy.constellation.tally.adapter.GvTypeAdapter : adapter
  com.yyzy.constellation.tally.fragment.TallyBaseFragment o-- com.yyzy.constellation.tally.bean.TallyLvItemBean : itemBean
  com.yyzy.constellation.tally.fragment.TallyBaseFragment o-- com.yyzy.constellation.utils.KeyBoardUtils : keyBoardUtils


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
