@startuml

title __BEAN's Class Diagram__\n

  namespace com.yyzy.constellation {
    namespace news {
      namespace bean {
        class com.yyzy.constellation.news.bean.NewsBean {
            - error_code : int
            - reason : String
            + getError_code()
            + getReason()
            + getResult()
            + setError_code()
            + setReason()
            + setResult()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace news {
      namespace bean {
        class com.yyzy.constellation.news.bean.NewsBean.ResultBean {
            - data : List<DataBean>
            - page : String
            - pageSize : String
            - stat : String
            + getData()
            + getPage()
            + getPageSize()
            + getStat()
            + setData()
            + setPage()
            + setPageSize()
            + setStat()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace news {
      namespace bean {
        class com.yyzy.constellation.news.bean.NewsBean.ResultBean.DataBean {
            - author_name : String
            - category : String
            - date : String
            - is_content : String
            - thumbnail_pic_s : String
            - thumbnail_pic_s02 : String
            - thumbnail_pic_s03 : String
            - title : String
            - uniquekey : String
            - url : String
            + getAuthor_name()
            + getCategory()
            + getDate()
            + getIs_content()
            + getThumbnail_pic_s()
            + getThumbnail_pic_s02()
            + getThumbnail_pic_s03()
            + getTitle()
            + getUniquekey()
            + getUrl()
            + setAuthor_name()
            + setCategory()
            + setDate()
            + setIs_content()
            + setThumbnail_pic_s()
            + setThumbnail_pic_s02()
            + setThumbnail_pic_s03()
            + setTitle()
            + setUniquekey()
            + setUrl()
        }
      }
    }
  }
  

  namespace com.yyzy.constellation {
    namespace news {
      namespace bean {
        class com.yyzy.constellation.news.bean.TypeBean {
            - id : int
            - isShow : boolean
            - title : String
            - url : String
            + TypeBean()
            + TypeBean()
            + getId()
            + getTitle()
            {static} + getTypeList()
            + getUrl()
            + isShow()
            + setId()
            + setShow()
            + setTitle()
            + setUrl()
        }
      }
    }
  }
  

  com.yyzy.constellation.news.bean.NewsBean o-- com.yyzy.constellation.news.bean.NewsBean.ResultBean : result
  com.yyzy.constellation.news.bean.NewsBean +-down- com.yyzy.constellation.news.bean.NewsBean.ResultBean
  com.yyzy.constellation.news.bean.NewsBean.ResultBean +-down- com.yyzy.constellation.news.bean.NewsBean.ResultBean.DataBean
  com.yyzy.constellation.news.bean.TypeBean .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
